export const SURVIVAL_WEIGHTS = {
  RESOURCE_HEALTH: 0.25,
  STORAGE_HEALTH: 0.20,
  HISTORICAL_STABILITY: 0.15,
  RISK_EXPOSURE: 0.20,
  SYSTEM_ACTIVITY: 0.10,
  PRESERVATION_READINESS: 0.10,
} as const;

export const SURVIVAL_THRESHOLDS = {
  HEALTHY_MIN: 80,
  STABLE_MIN: 60,
  AT_RISK_MIN: 35,
  // below 35 is CRITICAL
} as const;
